build-broker-binaries: Support --on-msentraid-build-branch

diff --git a/build-broker-binaries b/build-broker-binaries
--- a/build-broker-binaries
+++ b/build-broker-binaries
@@ -3,6 +3,9 @@
 set -eu
 set -x
 
+MSENTRAID_BUILD_DIR="../msentraid-broker-build-dir"
+LIBHIMMELBLAU_DIR="third_party/libhimmelblau"
+
 usage(){
     cat << EOF
 Usage: $0 [--version <version>] [-h|--help]
@@ -48,48 +51,84 @@ fi
 
 if [ -n "${MSENTRAID_BUILD_BRANCH:-}" ]; then
     ORIG_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+    ORIG_DIR=$(pwd)
 
-    # Make sure that the msentraid-build branch does not exist
-    git branch -D msentraid-build 2>/dev/null || true
+    # Export uncommitted changes from main repo
+    git diff > /tmp/uncommitted.patch
+    git diff --staged >> /tmp/uncommitted.patch
 
-    # Stash any uncommitted changes
-    git stash push -m "Stash before creating msentraid-build branch"
+    if ! git submodule status "${LIBHIMMELBLAU_DIR}" &> /dev/null; then
+        IGNORE_LIBHIMMELBLAU=1
+    fi
 
-    git -C third_party/libhimmelblau stash push -m "Stash before creating msentraid-build branch"
+    if [ -z "${IGNORE_LIBHIMMELBLAU:-}" ]; then
+        LIBHIMMELBLAU_COMMIT=$(git -C "${LIBHIMMELBLAU_DIR}" rev-parse HEAD)
+        git -C "${LIBHIMMELBLAU_DIR}" diff "${LIBHIMMELBLAU_COMMIT}" > /tmp/libhimmelblau_uncommitted.patch
+
+        # Ensure that the current commit of the libhimmelblau submodule is a reference that can be fetched
+        LIBHIMMELBLAU_BRANCH="msentraid-build-${RANDOM}"
+        git -C "${LIBHIMMELBLAU_DIR}" branch -f "${LIBHIMMELBLAU_BRANCH}" HEAD
+    fi
+
+    if [ ! -d "${MSENTRAID_BUILD_DIR}" ]; then
+        # Clone the msentraid build directory if it doesn't exist
+        git clone --recurse-submodules "$(pwd)" "${MSENTRAID_BUILD_DIR}"
+        git -C "${MSENTRAID_BUILD_DIR}/${LIBHIMMELBLAU_DIR}" remote set-url origin "${ORIG_DIR}/${LIBHIMMELBLAU_DIR}"
+    fi
+
+    # Switch to the msentraid build directory
+    pushd "${MSENTRAID_BUILD_DIR}"
+    git fetch origin
+    git -C "${LIBHIMMELBLAU_DIR}" fetch origin
+    git reset --hard
 
     # Create a new branch based on the msentraid branch with the commits that are not in the main branch cherry-picked
-    git checkout -b msentraid-build msentraid
-    git cherry-pick main..${ORIG_BRANCH}
+    git checkout msentraid-build
+    git reset --hard origin/msentraid
+    git cherry-pick --abort || true # Abort any previous cherry-pick operation
+    git cherry-pick origin/main..origin/"${ORIG_BRANCH}"
     git submodule update
 
-    # Pop the stash if it exists
-    if git stash list | head -n1 | grep -q "Stash before creating msentraid-build branch"; then
-        git stash pop --quiet
+    # Checkout the libhimmelblau commit in the submodule
+    if [ -z "${IGNORE_LIBHIMMELBLAU:-}" ]; then
+        git -C "${LIBHIMMELBLAU_DIR}" checkout "${LIBHIMMELBLAU_COMMIT}"
     fi
-    if git -C third_party/libhimmelblau stash list | head -n1 | grep -q "Stash before creating msentraid-build branch"; then
-        git -C third_party/libhimmelblau stash pop --quiet
+
+    # Apply uncommitted changes from the main repo
+    if [ -s /tmp/uncommitted.patch ]; then
+        git apply /tmp/uncommitted.patch
+    fi
+    if [ -s /tmp/libhimmelblau_uncommitted.patch ]; then
+        git -C "${LIBHIMMELBLAU_DIR}" apply /tmp/libhimmelblau_uncommitted.patch
+    fi
+
+    git restore-mtime
+    if [ -z "${IGNORE_LIBHIMMELBLAU:-}" ]; then
+        git -C "${LIBHIMMELBLAU_DIR}" restore-mtime
     fi
 
     cleanup() {
-        # Disable xtrace so that error messages during the build are easier to spot,
-        # as xtrace output would push them up and make them harder to find at the bottom.
-        set +x
+        echo >&2 "---------- Cleaning up ----------"
 
-        # Stash any uncommitted changes before returning to the original branch
-        git stash push --quiet -m "Stash before returning to original branch"
+        # Return to the original directory
+        popd
 
-        # Return to the original branch
-        git checkout --quiet "$ORIG_BRANCH"
-
-        # Pop the stash if it exists
-        if git stash list | head -n1 | grep -q "Stash before returning to original branch"; then
-            git stash pop --quiet
+        if [ -z "${IGNORE_LIBHIMMELBLAU:-}" ]; then
+            # Delete the temporary libhimmelblau branch
+            git -C "${LIBHIMMELBLAU_DIR}" branch -D "${LIBHIMMELBLAU_BRANCH}" || true
         fi
-        if git -C third_party/libhimmelblau stash list | head -n1 | grep -q "Stash before returning to original branch"; then
-            git -C third_party/libhimmelblau stash pop --quiet
+
+        # Print a message that the build failed if the exit code is non-zero
+        if [ "$EXIT_CODE" -ne 0 ]; then
+            echo >&2 "❌ Error: Build failed with exit code $EXIT_CODE, see above for details."
+            exit "$EXIT_CODE"
+        else
+            echo >&2 "✅ Build completed successfully."
         fi
     }
-    trap cleanup EXIT
+    if [ -z "${SKIP_CLEANUP:-}" ]; then
+        trap 'EXIT_CODE=$?; set +x; cleanup' EXIT
+    fi
 fi
 
 go mod vendor
@@ -100,6 +139,9 @@ if git grep -q authd-msentraid snap/snapcraft.yaml; then
     if [ -z "${SKIP_LIBHIMMELBLAU:-}" ]; then
         # Build the libhimmelblau binary and header
         go generate ./internal/providers/msentraid/...
+        if [ -n "${MSENTRAID_BUILD_BRANCH:-}" ]; then
+            cp ./internal/providers/msentraid/himmelblau.h "${ORIG_DIR}"/internal/providers/msentraid/himmelblau.h
+        fi
     fi
 elif git grep -q authd-google snap/snapcraft.yaml; then
     args="-tags=withgoogle -o authd-google"
