pre-push: Check golden files containing registered gRPC services

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -45,6 +45,17 @@ if [ -d ./cmd/authd-oidc ]; then
     go build -tags=withmsentraid -o /dev/null ./cmd/authd-oidc
 fi
 
+if [ -d internal/services ]; then
+    # Check if the golden files containing the registered gRPC services are up to date
+    TESTS_UPDATE_GOLDEN=1 go test -C internal/services -run TestRegisterGRPCServices
+    # Check if any files were modified
+    if [ -n "$(git status --porcelain)" ]; then
+        set +x
+        echo >&2 "pre-push: Error: internal/services: golden files were updated, please commit the changes"
+        FAILED=1
+    fi
+fi
+
 # Check if the strings "DO-NOT-PUSH" are present in the diff with main
 if git diff main | grep -e DO-NOT-PUSH | grep -v "mktemp"; then
     set +x
