pre-push: Check yamlfmt on .github

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -30,6 +30,13 @@ if ! golangci-lint run; then
     FAILED=1
 fi
 
+# Check yamlfmt on .github
+if ! go run github.com/google/yamlfmt/cmd/yamlfmt@latest -lint .github; then
+    set +x
+    echo >&2 "pre-push: Error: yamlfmt check failed on .github"
+    FAILED=1
+fi
+
 while read local_ref local_oid remote_ref remote_oid; do
     if [ "$local_oid" = "$zero" ]; then
         # Handle delete
